title: "Hacker News"
description: "Hacker News reader by GWC"
avatar: "https://guyswhocode.com/logo.jpg"
baseurl: "https://guyswhocode.com"

social:
  email: guyswhocode@gmail.com
  facebook: guyswhocode 
  github: guyswhocode 
  instagram: guyswhocode 
  linkedin: guyswhocode 
  pinterest: guyswhocode 
  skype: guyswhocode 
  twitter: guyswhoc0de 
  youtube: guyswhocode
