module.exports = {
  content: ["./src/**/*.njk", "./src/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-surface-variant": "#5a4136",
        "surface-container-low": "#f5f3f3",
        "on-secondary-fixed": "#1b1c1c",
        "primary-fixed-dim": "#ffb596",
        "on-error": "#ffffff",
        "inverse-primary": "#ffb596",
        "on-secondary-fixed-variant": "#464747",
        "on-tertiary-container": "#2e302b",
        "on-background": "#1b1b1b",
        "secondary-container": "#e3e2e2",
        "inverse-on-surface": "#f2f0f0",
        "surface-bright": "#faf9f9",
        "on-tertiary-fixed-variant": "#464743",
        "surface-tint": "#2B9720",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container": "#efeded",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbcd",
        "on-surface": "#1b1c1c",
        "on-secondary-container": "#646464",
        "on-primary-fixed-variant": "#7c2e00",
        tertiary: "#5d5f5a",
        "secondary-fixed": "#e3e2e2",
        "tertiary-fixed-dim": "#c6c7c0",
        "outline-variant": "#e3bfb1",
        "tertiary-fixed": "#e3e3dc",
        "on-tertiary-fixed": "#1a1c18",
        secondary: "#5e5e5e",
        primary: "#2B9720",
        "inverse-surface": "#303031",
        surface: "#faf9f9",
        "on-primary-fixed": "#0a2608",
        background: "#fefefe",
        "primary-container": "#2B9720",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e3e2e2",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#c7c6c6",
        "on-primary-container": "#ffffff",
        "surface-container-highest": "#e3e2e2",
        "surface-container-high": "#e9e8e8",
        "on-secondary": "#ffffff",
        outline: "#8e7164",
        "surface-dim": "#dbdad9",
        "tertiary-container": "#969791",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["IBM Plex Mono"],
        body: ["IBM Plex Mono"],
        label: ["IBM Plex Mono"],
      },
    },
  },
  plugins: [],
};
